services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    env_file:
      - ./backend/.env
    environment:
      - PORT=80
      - ENV=production
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - "./frontend/.env"
    environment:
      - PORT=80
    restart: always

networks:
  default:
    name: kitchen_iq_network